[theme]
base = "light"

# General color setup
textColor = "#000000ff"
primaryColor = "#000000ff"
backgroundColor = "#f1ececff"
secondaryBackgroundColor = "#b87377ff"

# Widgets
showWidgetBorder = true
borderColor = "#000000ff"

# Dataframes
dataframeHeaderBackgroundColor = "#000000ff"

# Base text
font = "'Bebas Neue':'https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
baseFontWeight = 300
baseFontSize = 14

# Heading text
headingFont = "Bebas Neue"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]